// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
namespace AssemblyCSharp
{
	public class debris
	{
		public string satName, category, epoch_year, satname2, satnamejpn, epoch, model, serial, payload, wikipedia, picture, vendor, launched, country, purpose, feature;
		public float longitude, latitude, altitude;

		public debris (string line)
		{
			string[] entries = line.Split ('\t');
			this.satName = entries[0];
			this.category = entries [1];
			this.epoch_year = entries [2];
			this.longitude = float.Parse(entries [3]);
			this.latitude = float.Parse (entries [4]);
			this.altitude = float.Parse (entries [5]);

			this.satname2 = entries [6];
			this.satnamejpn = entries [7];
			this.epoch = entries [8];
			this.model = entries [9];
			this.serial = entries [10];
			this.payload = entries [11];
			this.wikipedia = entries [12];
			this.picture = entries [13];
			this.vendor = entries [14];
			this.launched = entries [15];
			this.country = entries [16];
			this.purpose = entries [17];
			this.feature = entries [18];
		}

		public debris (string satName, float longitude, float latitude, float altitude)
		{
				this.satName = satName;
				this.longitude = longitude;
				this.latitude = latitude;
				this.altitude = altitude;
		}

		public static debris[] AllDebris ()
		{
			string[] lines = csvstring.Split(new [] { '\r', '\n' });

			debris[] all = new debris[(lines.Length)];
			for (int i = 0; i < lines.Length; i ++) {
				all[i] = new debris (lines[i]);
			}

			return all;
		}

		public static int Length () {
			return 1;
		}

		private static string csvstring = @"";
		}
}

